### ISSUE TITLE
Questions on data

### ISSUE THREAD

**Issue by jake3991** [giovgiac/son2sat#1]
Nice work! This is great stuff! I'm doing some similar work and hoping to use the provided dataset. 

I've got a few questions on this work below. 
1. The dataset provided here looks like it's used in the IROS paper "Matching Color Aerial Images and Underwater Sonar Images using Deep Learning for Underwater Localization" I'm curious are all the images in the provided dataset 100% overlap? If not how can I tell which images have what amount of overlap? 

2. What is the sonar used for this data? I'd like to know the brand, model and if the resolution is adjustable, what resolution is it set to during data collection.

**Comment by giovgiac** [comment]
Hello there!

So, to answer your questions:

1. This dataset here is slightly different, although the underlying dataset
it is produced from is the same. In the one provided for download here, all
images have 100% overlap. If I remember correctly, this is from after we
manually fixed the compass errors, so they should be pretty accurate,
otherwise there might be some misalignments. If you'd like to have access
to the IROS dataset I can upload it for you.

2. The sonar used is the Teledyne BlueView P900 with 130 degree field of
view and configured for a 50 m range for this specific dataset.

**Comment by jake3991** [comment]
Thanks for getting back to me!

It would be great to have access to the IROS dataset, could you upload it?

**Comment by giovgiac** [comment]
Done!

I placed the links in the repository that contains the IROS code:
giovgiac/neptune <https://github.com/giovgiac/neptune>

**Comment by jake3991** [comment]
Thanks!
